runner:
  total_steps: 200000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 100 #100
  eval_step: 5000 #5000
  save_step: 5000 #1000
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

downstream_expert:
  datarc:
    speech_commands_root: /work/u2752721/speech_commands_v0.01
    speech_commands_test_root: /work/u2752721/speech_commands_test_set_v0.01
    num_workers: 8
    batch_size: 32

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
